[package]
name = "testasyncsqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
libsqlite3-sys = "0.35.0"
rusqlite = "0.37.0"
sqlx = { git = "https://github.com/launchbadge/sqlx.git", version = "0.9.0-alpha.1", features = ["sqlite"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
